---
abstract: 'provides functions for generating lists'
author:
  - 'Eric Strom <asg@cpan.org>'
configure_requires:
  Module::Build: 0.37
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: https://metacpan.org/pod/CPAN::Meta::Spec
  version: 2
name: List-Gen
provides:
  List::Gen:
    file: lib/List/Gen.pm
    version: 0.975
  List::Gen::Benchmark:
    file: lib/List/Gen/Benchmark.pm
  List::Gen::Cookbook:
    file: lib/List/Gen/Cookbook.pm
  List::Gen::Haskell:
    file: lib/List/Gen/Haskell.pm
  List::Gen::Lazy:
    file: lib/List/Gen/Lazy.pm
  List::Gen::Lazy::Builtins:
    file: lib/List/Gen/Lazy/Builtins.pm
  List::Gen::Lazy::Ops:
    file: lib/List/Gen/Lazy/Ops.pm
  List::Gen::Perl6:
    file: lib/List/Gen/Perl6.pm
  List::Generator:
    file: lib/List/Generator.pm
requires:
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    web: https://github.com/jo-37/list-gen.git
    url: git://github.com/jo-37/list-gen.git
version: 0.976
